{
 "title": "Productie",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Huidig", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Productie",
   "type": "graph",
   "gridPos": { "h": 13, "w": 19, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "yaxes": [
    { "format": "kwatt" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time_stamp AS \"time\",\n  production\nFROM production\nWHERE\n  $__timeFilter(time_stamp)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Huidige productie",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_stamp AS \"time\",\n  production\nFROM production\nWHERE\n  $__timeFilter(time_stamp)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Gisteren",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_stamp AS \"time\",\n  production\nFROM production\nWHERE\n  $__timeFilter(time_stamp)\nORDER BY 1"
    }
   ]
  },
  { "title": "Gemiddeld", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Gemiddelde productie",
   "type": "graph",
   "gridPos": { "h": 12, "w": 19, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time_stamp,$__interval),\n  avg(production) AS \"production\"\nFROM production\nWHERE\n  $__timeFilter(time_stamp)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Nu",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time_stamp,$__interval),\n  avg(production) AS \"production\"\nFROM production\nWHERE\n  $__timeFilter(time_stamp)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Gisteren",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time_stamp,$__interval),\n  avg(production) AS \"production\"\nFROM production\nWHERE\n  $__timeFilter(time_stamp)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  { "title": "kwh totaal", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "kWh consumptie",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_stamp AS \"time\",\n  tariff1_consumed,\n  tariff2_consumed,\n  tariff1_consumed+tariff2_consumed as total_consumption\nFROM production\nWHERE\n  $__timeFilter(time_stamp)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "kWh productie",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_stamp AS \"time\",\n  tariff1_produced,\n  tariff2_produced,\n  tariff1_produced+tariff2_produced as total_production\nFROM production\nWHERE\n  $__timeFilter(time_stamp)\nORDER BY 1"
    }
   ]
  }
 ]
}